- hosts: all 
  
  remote_user: lmora
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - ~/vault.yml
  
  vars:
    ssh_key_filename: id_rsa
    ansible_become_pass: '{{vault_ansible_become_pass}}'

  tasks:
    - name: Create Group
      group:
        name: ansible
        state: present

    - name: Create User 
      user: 
        name: ansible
        password: '$6$yax3iL0g5n1YXJ6b$MJrNHk4MaTdVezos8/3ncbhjwFwhCNjcAG.dAPp2L6QR1iFOtnGgWBN6dBbdgOiqkrkZyhlYJD8iAoZjVgnD9/'
        groups:
          - ansible
          - sudo
          - www-data
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/ansible 
    - name: Generate SSH key "{{ssh_key_filename}}"
      user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_file: .ssh/{{ssh_key_filename}}
        type: rsa
        size: 4096
        state: present
        force: no
